package com.vidora.app.presentation.navigation.main

sealed class Screen(val route: String){
    object Splash: Screen("splash")
    object Login: Screen("login")
    object SignUp: Screen("signup")
    object ForgetPassword: Screen("forget-password")
    object Main: Screen("main")
    object CreateChannelScreen: Screen("create-channel")
    object MainChannelScreen: Screen("main-channel/{channelId}")
    object EditChannel: Screen("edit-channel/{channelId}")
    object UserVideoScreen: Screen("user-video-screen")
    object UploadVideoScreen: Screen("upload-video")
    object VideoDetailScreen: Screen("videoPreview/{uri}")
    object EditVideoScreen: Screen("editVideo/{id}")
    object PublicVideoScreen: Screen("publicVideo/{videoId}")
    object PublicChannelScreen: Screen("publicChannel/{channelId}")
    object SearchScreen: Screen("search-screen")
    object SearchResultScreen: Screen("searchResults/{query}")
    object MySubscriptionScreen: Screen("allMySubscription")
    object WatchHistory: Screen("watchHistory")
    object WatchLater: Screen("savedVideos")
    object DownloadScreen: Screen("downloadVideos")
    object HelpScreen: Screen("helpAndSupport")
    object PrivacyScreen: Screen("privacy-policy")
    object TermsScreen: Screen("terms-conditions")
    object AboutUsScreen: Screen("about-us")
    object AnalyticsScreen: Screen("analytics-screen")
}